aws-region  = "eu-west-2"
aws-profile = "ds-web-products-staging"
instance-tag-name = "App-Engagement-Ec2"
user-data-script = "./user-data.sh"
instance-key-name = "engage-key"
iam-role-name     = "engage-ECR-read"
instance-ami      = "ami-01419b804382064e4"
